# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.DotNet.Runtime.6
PackageVersion: 6.0.3
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
Installers:
- Architecture: arm64
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.3/dotnet-runtime-6.0.3-win-arm64.exe
  InstallerSha256: 1A763D714C69F7DC3978DBB5F45D67E1794C36A5CAC4BDE1A15C6C020FDAC6E3
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.3/dotnet-runtime-6.0.3-win-x64.exe
  InstallerSha256: 5FE87720A937E765D6D2E6FD279AB71BEE463CE4A41039AB6882B3C7A997B67D
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.3/dotnet-runtime-6.0.3-win-x86.exe
  InstallerSha256: DB8360D878FD9C2A3C37883AF1C13D51536A26942DD1296693B9AFA5B22EDDB9
ManifestType: installer
ManifestVersion: 1.1.0

