# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
PackageVersion: 6.0.3
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
Installers:
- Architecture: arm64
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.3/windowsdesktop-runtime-6.0.3-win-arm64.exe
  InstallerSha256: 9BA62B975E3671FB980BC4FDFCDF75144EE7C3951024080B6765B5392BD42035
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.3/windowsdesktop-runtime-6.0.3-win-x64.exe
  InstallerSha256: F331A611EF50EDC79654868AE2C3B5A968D1F462841AC6990B6B353D23C157EA
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.3/windowsdesktop-runtime-6.0.3-win-x86.exe
  InstallerSha256: 0F373AA1AEAD86E54992A3E70328115AA31E19EEDA625BDCE55C78870669CC34
ManifestType: installer
ManifestVersion: 1.1.0

