# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.DotNet.HostingBundle.Preview
PackageVersion: 7.0.0-preview.2.22153.2
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
Installers:
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/7.0.0-preview.2.22153.2/dotnet-hosting-7.0.0-preview.2.22153.2-win.exe
  InstallerSha256: 1C39C662E1109665FA5A818551C287DEFFC308849E22A0E4E5DAD756D8F474B9
ManifestType: installer
ManifestVersion: 1.1.0

